# Generated by Django 3.1.7 on 2021-03-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
                ('email', models.CharField(max_length=10, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
