# Generated by Django 3.1.7 on 2021-03-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduation_design', '0003_auto_20210326_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wel_login',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='邮箱'),
        ),
    ]
