# Generated by Django 3.1.7 on 2021-03-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduation_design', '0004_auto_20210326_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wel_login',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='wel_login',
            name='password',
            field=models.CharField(max_length=50, verbose_name='普通密码'),
        ),
        migrations.AlterField(
            model_name='wel_login',
            name='user',
            field=models.CharField(max_length=50, verbose_name='普通用户名'),
        ),
    ]
