# Generated by Django 3.1.7 on 2021-03-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduation_design', '0007_auto_20210327_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
    ]
