# Generated by Django 3.1.7 on 2021-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduation_design', '0008_auto_20210329_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'me',
            },
        ),
    ]
