# Generated by Django 3.1.7 on 2021-03-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graduation_design', '0009_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Me',
        ),
    ]
